### ISSUE TITLE
last-train + repeat masking + code

### ISSUE THREAD

**Issue by GuillaumeHolley** [mcfrith/dnarrange#1]
Hi,

I just read your recently published paper "A pipeline for complete characterization of complex germline rearrangements from long DNA reads" and I found it very interesting, thank you for this work. I am trying to go through your pipeline [here](https://github.com/mcfrith/dnarrange) and [here](https://github.com/mcfrith/last-rna/blob/master/last-long-reads.md). I have a couple of questions regarding step 1:

- ~~I have installed the latest version of `last` (v1080) but I cannot find the binary for `last-train` which is used in your pipeline to compute indels and substitutions rate. As a measure of precaution, I also download v983 but again, all `last` binaries are there except `last-train`.~~ I just found it, it is in a different folder, sorry about that.

- On this [page](https://github.com/mcfrith/last-rna/blob/master/last-long-reads.md), you describe how to repeat-mask the reference genome. I download the reference genome `hg38.analysisSet` as you mentioned in Appendix A and it seems to me that the chromosomes have already been repeat-masked. Do I still need to do the repeat-masking procedure in that case?

- I see that your repository for `dnarrange` ([here](https://github.com/mcfrith/dnarrange)) contains only binaries. Will you also make the code available?

Thank you for help and time.
Guillaume

**Comment by mcfrith** [comment]
Thanks for reading our paper so soon!

I recommend doing the repeat-masking procedure. I believe the downloaded reference was masked in a different way (RepeatMasker versus WindowMasker). I tested this several years ago: as I recall, our recommended masking works better for our specific needs. (This is a weak point of our pipeline: lastdb should automatically do masking optimized for our needs.)

Those files in dnarrange are Python code :)
